SELECT A.AUTHOR_ID, 
       A.AUTHOR_NAME, 
       B.CATEGORY, 
       SUM(BS.SALES * B.PRICE)  AS TOTAL_SALES

  FROM BOOK B,
       AUTHOR A,
       BOOK_SALES BS
       
 WHERE B.BOOK_ID = BS.BOOK_ID
   AND A.AUTHOR_ID = B.AUTHOR_ID
   AND BS.SALES_DATE BETWEEN '2021-12-31' AND '2022-01-31'
   
  GROUP BY A.AUTHOR_ID, B.CATEGORY
  ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
